### ISSUE TITLE
Dedicated server crash on player death

### ISSUE THREAD

**Issue by Not-February** [quat1024/WorseBarrels#1]
https://hastebin.com/piviferatu.rb

This was experienced by another player as they respawned in an area with barrels placed. I can ask for more information if needed.

**Comment by quat1024** [comment]
I dunno if it's just me, but that is a blank page

**Comment by Not-February** [comment]
It's not blank to me(just checked), but I'll put it on pastebin too.

https://pastebin.com/wJieiLuH

**Comment by quat1024** [comment]
This should be fixed since a while ago.
