### ISSUE TITLE
Can't sneak-click a stack into or out of a barrel if sneak is remapped

### ISSUE THREAD

**Issue by GeorgeEbberson** [quat1024/WorseBarrels#2]
If sneak is remapped to anything other than LSHIFT, sneak-clicking and sneak-right clicking to add and remove stacks does not work.

To reproduce:
Remap sneak to LCONTROL, then try and LCONTROL+RCLICK to move a stack of items into the barrel.

**Comment by quat1024** [comment]
For now, in the options menu for the mod, you can remap ctrl-leftclick and ctrl-rightclick actions to do something else.

This is why it happens: https://github.com/quat1024/WorseBarrels/blob/abf70428d4fea9e567274036d1ecd3198b097326/src/main/java/quaternary/worsebarrels/proxy/ClientProxy.java#L23-L29

In an update I'll make it check for sneaking first, then ctrl.
